name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 4 * * 6' # Every Saturday at 04:00 UTC
    - cron: '0 4 * * 3' # Every Wednesday at 04:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  esphome_version:
    name: Get ESPHome Version
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6

      - name: Get ESPHome image tag from Dockerfile
        id: get_tag
        run: |
          TAG=$(grep '^FROM ghcr.io/esphome/esphome:' Dockerfile | head -n1 | cut -d: -f2)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Using ESPHome version: **${TAG}**" >> $GITHUB_STEP_SUMMARY

  ble_remote:
    name: BLE Remote
    runs-on: ubuntu-latest
    needs: esphome_version
    strategy:
      matrix:
        component:
          - ble_remote
          - ble_remote_receiver
        esphome_version:
          - ${{ needs.esphome_version.outputs.tag }}
        esp32_variant:
          - esp32
          - esp32c3
          - esp32s3
        toolchain:
          - platformio
          - esp-idf
        include:
          - esphome_version: "2026.5.0"
            component: ble_remote
            esp32_variant: esp32
            toolchain: platformio
          - esphome_version: "2026.5.0"
            component: ble_remote_receiver
            esp32_variant: esp32
            toolchain: platformio
    container:
      image: ghcr.io/esphome/esphome:${{ matrix.esphome_version }}
      volumes:
        - /github/home/.cache:/github/home/.cache
        - /github/home/.platformio:/github/home/.platformio
    env:
      YAML_FILE: example_${{ matrix.component }}.yaml
      ESPHOME_ESP_IDF_PREFIX: ${{ github.workspace }}/.esphome/idf
      IDF_CCACHE_ENABLE: 1
    steps:
      - uses: actions/checkout@v6

      - name: Set local component path
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.external_components[0].source = "./components"' ${{ env.YAML_FILE }}

      - name: Set esp32 variant
        uses: mikefarah/yq@v4
        with:
          cmd: yq -i '.esp32.variant = "${{ matrix.esp32_variant }}"' ${{ env.YAML_FILE }}

      - name: Prepare secrets
        run: |-
          echo "wifi_ssid: TEST" >> secrets.yaml
          echo "wifi_password: testtest" >> secrets.yaml
          echo "ble_remote_shared_key: TEST1234" >> secrets.yaml

      - name: Generate cache key
        run: |-
          echo "ESPHOME_VERSION=$(esphome version)" >> $GITHUB_ENV
          echo "ESPHOME_VER_HASH=$(esphome version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: |-
            ~/.cache/ccache
            ~/.cache/pip
            ~/.platformio/.cache
            ~/.platformio/packages
            .esphome/idf/frameworks
            .esphome/idf/penvs
            .esphome/idf/tools/cmake
            .esphome/idf/tools/ninja
            .esphome/idf/tools/esp32ulp-elf
            .esphome/idf/tools/openocd-esp32
          key: ${{ runner.os }}-esphome-${{ env.ESPHOME_VER_HASH }}-${{ matrix.toolchain }}

      - name: Build
        run: esphome --toolchain "$TOOLCHAIN" compile "$YAML_FILE"
        env:
          TOOLCHAIN: ${{ matrix.toolchain }}

      - name: Add build summary
        if: always()
        run: |
          echo "- **Device Name:** ${{ matrix.esp32_variant }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Toolchain:** ${{ matrix.toolchain }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Config File:** ${{ env.YAML_FILE }}" >> $GITHUB_STEP_SUMMARY
          echo "- **ESPHome Version:** ${{ env.ESPHOME_VERSION }}" >> $GITHUB_STEP_SUMMARY

  build_ok:
    name: Build
    runs-on: ubuntu-latest
    needs: ble_remote
    steps:
      - run: echo OK
